INSERT INTO produtos (id, nome, url_imagem, descricao, preco, classificacao) VALUES
  (1, 'Smartphone X', 'https://example.com/imagens/smartphone-x.png', 'Smartphone com tela OLED e camera dupla.', 3599.90, 4.5),
  (2, 'Notebook Pro', 'https://example.com/imagens/notebook-pro.png', 'Notebook leve com bateria de longa duracao.', 7499.00, 4.7),
  (3, 'Fone Sem Fio', 'https://example.com/imagens/fone-sem-fio.png', 'Fones bluetooth com cancelamento de ruido.', 899.00, 4.2),
  (4, 'Smartwatch Active', 'https://example.com/imagens/smartwatch-active.png', 'Relogio inteligente com GPS e monitoramento de saude.', 1299.50, 4.4),
  (5, 'Camera Action', 'https://example.com/imagens/camera-action.png', 'Camera de acao a prova d agua com 4K.', 1799.00, 4.3),
  (6, 'Tablet Max', 'https://example.com/imagens/tablet-max.png', 'Tablet com caneta e tela de 11 polegadas.', 2899.99, 4.6),
  (7, 'Monitor UltraWide', 'https://example.com/imagens/monitor-ultrawide.png', 'Monitor 34 polegadas para produtividade e jogos.', 2499.00, 4.8),
  (8, 'Teclado Mecanico', 'https://example.com/imagens/teclado-mecanico.png', 'Teclado RGB com switches silenciosos.', 599.90, 4.1),
  (9, 'Mouse Gamer', 'https://example.com/imagens/mouse-gamer.png', 'Mouse ergonomico com alta precisao.', 349.90, 4.0),
  (10, 'Roteador WiFi 6', 'https://example.com/imagens/roteador-wifi6.png', 'Roteador gigabit com WiFi 6 e OFDMA.', 799.00, 4.4),
  (11, 'Headset Pro', 'https://example.com/imagens/headset-pro.png', 'Headset com som surround 7.1 e microfone removivel.', 699.00, 4.2),
  (12, 'SSD NVMe 1TB', 'https://example.com/imagens/ssd-nvme.png', 'SSD NVMe com alta performance de leitura e escrita.', 699.90, 4.9),
  (13, 'HD Externo 4TB', 'https://example.com/imagens/hd-externo.png', 'HD externo portatil com backup automatico.', 649.00, 4.3),
  (14, 'Caixa de Som Bluetooth', 'https://example.com/imagens/caixa-som.png', 'Caixa de som resistente a agua com som 360.', 499.00, 4.5),
  (15, 'Projetor Portatil', 'https://example.com/imagens/projetor-portatil.png', 'Projetor compacto com bateria integrada.', 2149.00, 4.1),
  (16, 'Cadeira Gamer', 'https://example.com/imagens/cadeira-gamer.png', 'Cadeira ergonomica com ajuste lombar.', 1299.00, 4.0),
  (17, 'Webcam Full HD', 'https://example.com/imagens/webcam-fullhd.png', 'Webcam com microfone e suporte para streaming.', 399.90, 4.2),
  (18, 'Microfone USB', 'https://example.com/imagens/microfone-usb.png', 'Microfone condensador para podcast e streaming.', 549.00, 4.6),
  (19, 'Placa de Video 8GB', 'https://example.com/imagens/gpu-8gb.png', 'Placa dedicada para jogos em 1080p.', 2299.00, 4.4),
  (20, 'Processador Octa', 'https://example.com/imagens/processador-octa.png', 'Processador octa-core para desktops.', 1799.00, 4.7),
  (21, 'Memoria RAM 16GB', 'https://example.com/imagens/ram-16gb.png', 'Kit DDR5 de alta frequencia.', 699.00, 4.8),
  (22, 'Fonte Modular 750W', 'https://example.com/imagens/fonte-750w.png', 'Fonte certificada 80 Plus Gold.', 799.00, 4.5),
  (23, 'Gabinete ATX', 'https://example.com/imagens/gabinete-atx.png', 'Gabinete com painel de vidro temperado.', 599.90, 4.1),
  (24, 'Placa Mae Gaming', 'https://example.com/imagens/placa-mae.png', 'Placa mae com suporte DDR5 e WiFi integrado.', 1499.00, 4.6),
  (25, 'Cooler Liquido', 'https://example.com/imagens/cooler-liquido.png', 'Water cooler com radiador de 240mm.', 749.00, 4.4),
  (26, 'Impressora Laser', 'https://example.com/imagens/impressora-laser.png', 'Impressora laser monocromatica rapida.', 1199.00, 4.0),
  (27, 'Scanner Portatil', 'https://example.com/imagens/scanner-portatil.png', 'Scanner compacto alimentado por USB.', 499.00, 4.2),
  (28, 'Desktop All-in-One', 'https://example.com/imagens/all-in-one.png', 'Computador all-in-one com tela de 24 polegadas.', 3799.00, 4.3),
  (29, 'Chromebook Slim', 'https://example.com/imagens/chromebook-slim.png', 'Chromebook leve para estudos e produtividade.', 2299.00, 4.1),
  (30, 'Hub USB-C', 'https://example.com/imagens/hub-usbc.png', 'Hub com HDMI, USB e leitor de cartoes.', 279.90, 4.0),
  (31, 'Carregador GaN', 'https://example.com/imagens/carregador-gan.png', 'Carregador rapido compacto 65W.', 249.90, 4.5),
  (32, 'Power Bank 20k', 'https://example.com/imagens/powerbank.png', 'Bateria externa de 20.000mAh com PD.', 329.90, 4.4),
  (33, 'Cabo HDMI 8K', 'https://example.com/imagens/cabo-hdmi.png', 'Cabo HDMI certificado para 8K.', 129.90, 4.7),
  (34, 'Adaptador Bluetooth', 'https://example.com/imagens/adaptador-bt.png', 'Adaptador USB Bluetooth 5.3.', 99.90, 4.3),
  (35, 'Switch Gigabit', 'https://example.com/imagens/switch-gigabit.png', 'Switch com 8 portas gigabit.', 349.90, 4.2),
  (36, 'NAS Case', 'https://example.com/imagens/nas-case.png', 'Gabinete para NAS com 4 baias.', 1099.00, 4.1),
  (37, 'Servidor Micro', 'https://example.com/imagens/servidor-micro.png', 'Servidor compacto para laboratorio domestico.', 2899.00, 4.5),
  (38, 'Ventoinha RGB', 'https://example.com/imagens/ventoinha-rgb.png', 'Kit com tres ventoinhas RGB silenciosas.', 229.90, 4.0),
  (39, 'Suporte Notebook', 'https://example.com/imagens/suporte-notebook.png', 'Suporte ajustavel em aluminio.', 199.90, 4.4),
  (40, 'Dock Station', 'https://example.com/imagens/dock-station.png', 'Dock para notebook com diversas portas.', 1199.00, 4.6),
  (41, 'Filtro de Linha', 'https://example.com/imagens/filtro-linha.png', 'Filtro com protecao contra surtos.', 89.90, 4.1),
  (42, 'Repetidor WiFi', 'https://example.com/imagens/repetidor-wifi.png', 'Repetidor dual-band facil de configurar.', 159.90, 4.0),
  (43, 'Smart Lamp', 'https://example.com/imagens/smart-lamp.png', 'Lampada inteligente com ajuste de cor.', 119.90, 4.3),
  (44, 'Smart Plug', 'https://example.com/imagens/smart-plug.png', 'Tomada inteligente com medidor de energia.', 139.90, 4.4),
  (45, 'Robo Aspirador', 'https://example.com/imagens/robo-aspirador.png', 'Aspirador robotico com mapeamento a laser.', 2299.00, 4.6),
  (46, 'Purificador de Ar', 'https://example.com/imagens/purificador.png', 'Purificador com filtro HEPA.', 1599.00, 4.3),
  (47, 'Cafeteira Automatica', 'https://example.com/imagens/cafeteira.png', 'Cafeteira expresso com moagem integrada.', 2499.00, 4.7),
  (48, 'Liquidificador Smart', 'https://example.com/imagens/liquidificador.png', 'Liquidificador com programas automatizados.', 799.90, 4.2),
  (49, 'Balança Inteligente', 'https://example.com/imagens/balanca.png', 'Balanca corporal com app.', 299.90, 4.1),
  (50, 'Aquecedor Portatil', 'https://example.com/imagens/aquecedor.png', 'Aquecedor portatil silencioso.', 449.90, 4.0);

INSERT INTO produto_especificacoes (produto_id, nome, valor) VALUES
  (1, 'Tela', '6.1 polegadas OLED'), (1, 'Memoria', '8GB RAM, 256GB armazenamento'),
  (2, 'Tela', '14 polegadas IPS'), (2, 'Processador', 'Intel i7 13a geracao'),
  (3, 'Autonomia', '30 horas'), (3, 'Resistencia', 'IPX5'),
  (4, 'GPS', 'Multibanda'), (4, 'Saude', 'Oxigenacao e batimentos'),
  (5, 'Video', '4K60'), (5, 'Resistencia', '50m agua'),
  (6, 'Caneta', 'Suporte a stylus'), (6, 'Tela', '11 polegadas 120Hz'),
  (7, 'Resolucao', '3440x1440'), (7, 'Taxa', '144Hz'),
  (8, 'Switch', 'Silencioso'), (8, 'Layout', 'ABNT2'),
  (9, 'DPI', '26000'), (9, 'Iluminacao', 'RGB'),
  (10, 'Padrão', 'WiFi 6'), (10, 'Portas', '4x Gigabit'),
  (11, 'Audio', 'Surround 7.1'), (11, 'Microfone', 'Removivel'),
  (12, 'Leitura', '7000MB/s'), (12, 'Gravacao', '6500MB/s'),
  (13, 'Capacidade', '4TB'), (13, 'Backup', 'Automatico'),
  (14, 'Som', '360 graus'), (14, 'Bateria', '20 horas'),
  (15, 'Brilho', '500 lumens'), (15, 'Bateria', '3 horas'),
  (16, 'Material', 'Couro sintetico'), (16, 'Ajuste', 'Altura e inclinacao'),
  (17, 'Resolucao', '1080p'), (17, 'FPS', '60fps'),
  (18, 'Padrao', 'Cardioide'), (18, 'Conexao', 'USB-C'),
  (19, 'Memoria', '8GB GDDR6'), (19, 'Saida', 'HDMI 2.1'),
  (20, 'Nucleos', '8 cores'), (20, 'Frequencia', '4.8GHz boost'),
  (21, 'Tipo', 'DDR5'), (21, 'Frequencia', '6000MHz'),
  (22, 'Certificacao', '80 Plus Gold'), (22, 'Cabo', 'Totalmente modular'),
  (23, 'Ventilacao', 'Frontal mesh'), (23, 'Baias', '3x 2.5'),
  (24, 'Chipset', 'Z790'), (24, 'Wireless', 'WiFi 7'),
  (25, 'Radiador', '240mm'), (25, 'Fans', '2x120mm'),
  (26, 'Velocidade', '30ppm'), (26, 'Conectividade', 'WiFi e USB'),
  (27, 'Alimentacao', 'USB'), (27, 'Formato', 'A4'),
  (28, 'Processador', 'Intel i5'), (28, 'Memoria', '8GB RAM'),
  (29, 'Peso', '1.1kg'), (29, 'Bateria', '12 horas'),
  (30, 'Portas', '3xUSB + HDMI'), (30, 'Cartao', 'SD e microSD'),
  (31, 'Potencia', '65W'), (31, 'Portas', '2xUSB-C + USB-A'),
  (32, 'Capacidade', '20000mAh'), (32, 'Carregamento', 'PD 45W'),
  (33, 'Versao', 'HDMI 2.1'), (33, 'Comprimento', '2 metros'),
  (34, 'Bluetooth', '5.3'), (34, 'Alcance', '20 metros'),
  (35, 'Portas', '8 gigabit'), (35, 'Funcoes', 'QoS basico'),
  (36, 'Baias', '4'), (36, 'Rede', '2x 2.5GbE'),
  (37, 'Memoria', '32GB RAM'), (37, 'Armazenamento', '2TB SSD'),
  (38, 'Tamanho', '120mm'), (38, 'Iluminacao', 'ARGB'),
  (39, 'Material', 'Aluminio'), (39, 'Ajuste', 'Altura regulavel'),
  (40, 'Portas', '2xHDMI, 3xUSB'), (40, 'Rede', 'Gigabit LAN'),
  (41, 'Tomadas', '6'), (41, 'Protecao', '1800 joules'),
  (42, 'Banda', '2.4 e 5GHz'), (42, 'Antenas', '2 externas'),
  (43, 'Lumens', '806'), (43, 'Temperatura', '2700K-6500K'),
  (44, 'Corrente', '10A'), (44, 'Monitoramento', 'Consumo em tempo real'),
  (45, 'Mapa', 'Laser Lidar'), (45, 'Autonomia', '120 minutos'),
  (46, 'Filtro', 'HEPA H13'), (46, 'Area', '50m2'),
  (47, 'Pressao', '19 bars'), (47, 'Reservatorio', '1.8L'),
  (48, 'Programas', '8 funcoes'), (48, 'Jarra', '1.7L'),
  (49, 'Sensores', 'Bioimpedancia'), (49, 'Usuarios', '8 perfis'),
  (50, 'Potencia', '1500W'), (50, 'Seguranca', 'Desligamento automatico');
